# Generated by Django 4.1.3 on 2022-11-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detect',
            name='left_eye',
        ),
        migrations.RemoveField(
            model_name='detect',
            name='right_eye',
        ),
    ]
